### ISSUE TITLE
Data availability/persistence

### ISSUE THREAD

**Issue by shortthefomo** [Xahau/JS-xPOP-Retrieve-Generate#1]
If I use the old example hash 20D193C6E615D86BCC13A5DAB781852A6672F3E627D33FBAE62053F1178740BB none of the existing pop services return a result.

I would have thought at least 1 would, is there maybe not a bug that those don't check old results after a reboot?

**Comment by WietseWind** [comment]
xPOP source data is simply stored on the filesystem, so it's either there or not. xPOP source data requires a lot of storage, so I assume everyone is running with the default docker compose that comes with periodic clean up.

If shit hits the fan, it can easily be reconstructed from data elsewhere, and I know XRPScan is storing all validation messages forever. Other data can be fetched from full history.

This can reconstruct: 

https://github.com/Xahau/Validation-Ledger-Tx-Store-to-xPOP/blob/main/lib/xpopGenerate.mjs

xPOPs must be minted asap after burning, as they also need to be imported in order. So fetching really old ones isn't something that really has a valid use case.

xPOPs get stored in two ways: ready to use with the hash as filename. These get cleaned up fast.

They can also be client side reconstructed (see link above, non xpop lib.) with raw validation message source data and UNL and ledger and tx metadata. 

That data is configured to be longer available.

Best availability check is thus with the npm package, knowing that best practice is to import shortly after burn, and that worst case it can be constructed from validation messages stored longer term like with Hermes by XRPscan.

Finally: you won't find your example tx because it isn't one?

https://test.bithomp.com/explorer/20D193C6E615D86BCC13A5DAB781852A6672F3E627D33FBAE62053F1178740BB

https://bithomp.com/explorer/20D193C6E615D86BCC13A5DAB781852A6672F3E627D33FBAE62053F1178740BB
